#!/bin/bash
#This script forces Snow Leopard (10.6) to build using Leopard (10.5)
# to build a 32 bit build.
# Use it when building livCVD, GVars, and lib3ds
#
# Originally wirrten by Damian Stewart
# http://lists.nongnu.org/archive/html/libcvd-members/2010-05/msg00000.html
# Modified by Robert Castle

SDK="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk"
SDKLIB="-Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk"
export MACOSX_DEPLOYMENT_TARGET="10.9"

ARCH="-arch i386"

export CFLAGS="$ARCH $SDK -mmacosx-version-min=10.9 -m32 -D_OSX -I/usr/local/include -I/usr/local/include/TooN"
export CXXFLAGS="$ARCH $SDK -mmacosx-version-min=10.9 -m32 -D_OSX -I/usr/local/include -I/usr/local/include/TooN"
export CPPFLAGS="$ARCH $SDK -mmacosx-version-min=10.9 -m32 -D_OSX -I/usr/local/include -I/usr/local/include/TooN"
export LDFLAGS="$ARCH $SDKLIB -mmacosx-version-min=10.9 -m32 -L/usr/local/lib"

#CC="clang"
#CXX="/usr/bin/g++-4.2"
#OBJC="/usr/bin/gcc-4.2"

./configure  --disable-debug --with-optimize="-O1" $1 $2 $3 $4 $5 $6 $7 $8 $9

